default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sulav
  password: sulavar
  host: localhost
  port: 5432

development:
  <<: *default
  database: store_app_development

test:
  <<: *default
  database: store_app_test

production:
  <<: *default
  database: store_app_production
